Revert "refactoring bash into task to see of timeout sticks"
This reverts commit d6de0b7738d0098b536250ad4a803beac3f937f7.

diff --git a/azure-pipelines/main.yml b/azure-pipelines/main.yml
--- a/azure-pipelines/main.yml
+++ b/azure-pipelines/main.yml
@@ -38,42 +38,39 @@ stages:
               popd
             displayName: "Configure a default TF2 build"
           - template : templates/wheel-version.yml
-          - task: Bash@3
-            timeoutInMinutes: 1440
-            inputs:
-              targetType: inline
-              script: |
-                # Doesn't work if installed in just the env, for includes
-                # specific to TF 2.3.0 -- restrict numpy version.
-                python -m pip install -U "numpy${NUMPY_VERSION}"
+          - bash: |
+              # Doesn't work if installed in just the env, for includes
+              # specific to TF 2.3.0 -- restrict numpy version.
+              python -m pip install -U "numpy${NUMPY_VERSION}"
 
-                source $PENV_HOME/bin/activate
-                echo switched to venv python: $(which python)
-                gcc --version
-                bazelisk --version
+              source $PENV_HOME/bin/activate
+              echo switched to venv python: $(which python)
+              gcc --version
+              bazelisk --version
 
-                python -m pip install -U "numpy${NUMPY_VERSION}"
-                python -m pip install -U keras_preprocessing --no-deps
-                python -m pip install -U keras_applications --no-deps
+              python -m pip install -U "numpy${NUMPY_VERSION}"
+              python -m pip install -U keras_preprocessing --no-deps
+              python -m pip install -U keras_applications --no-deps
 
-                # Retry for spurious failures. Bazel should cache successful steps.
-                for i in 1 2; do
+              # Retry for spurious failures. Bazel should cache successful steps.
+              for i in 1 2; do
 
-                  echo Compilation attempt $i...
+                echo Compilation attempt $i...
 
-                  bazelisk $BAZEL_STARTUP_OPTS build $BAZEL_BUILD_OPTS //tensorflow/tools/pip_package:build_pip_package
-                  compile_result="$?"
-                  if [[ compile_result == 0 ]]; then
-                    break
-                  fi
-                done
-
-                if [[ compile_result != 0 ]]; then
-                  echo Compilation failed after $i attempts.
+                bazelisk $BAZEL_STARTUP_OPTS build $BAZEL_BUILD_OPTS //tensorflow/tools/pip_package:build_pip_package
+                compile_result="$?"
+                if [[ compile_result == 0 ]]; then
+                  break
                 fi
+              done
 
-                exit $compile_result
+              if [[ compile_result != 0 ]]; then
+                echo Compilation failed after $i attempts.
+              fi
+
+              exit $compile_result
             displayName: 'Bazel build'
+            timeoutInMinutes: 1440
           - bash: |
               source $PENV_HOME/bin/activate
               echo switched to venv python: $(which python)
